function buy_direct(e,t,o,r,n,l,d,i,u,a,c){var m=0,s=ProductOptionColor="",_="",p="",v=0,f="",g=0
if("View_Box"==i&&!e)return void alert("구매하실 제품을 선택을 해주세요")
if((391605==e||391608==e)&&document.global_form.add_ProductNo&&$("#last_461244").val()){var y=(document.global_form.add_ProductNo.value,$("#last_461244").val()),h=$("#last_ea1").val()
if(y>h)return}if(null!=document.getElementById("last_ea1")&&document.getElementById("last_ea1").value)var E=document.getElementById("last_ea1").value,I=E.split(","),m=I[0]
if(m>0&&(o=m),"행사"!=t&&"N"==l)return void alert("해당 제품은 로그인 후 구매 하실 수 있습니다. (한정판매)")
if("행사"==t&&"N"==l)return alert("행사 제품은 로그인 후 구매 하실 수 있습니다."),void login()
if(0!=l&&+o>+l)return void alert("해당 제품은 일일 구매개수가 "+l+"개로 한정되어 있습니다.")
var P="Y"
if("옵션"==t&&(P=""),"BuyList"==i){for(var w=0,B=e,b=0;B>b;b++)for(var x=document.getElementById("AddGroupCount_"+b).value,N=0;x>N;N++)1==document.getElementById("GroupNo_"+b+"_"+N).checked&&(ProductOption_one=document.getElementById("GroupNo_"+b+"_"+N).value+"|",ProductOptionea_tow=document.getElementById("GroupProductea_"+b+"_"+N).value+"|",0==w?(e=ProductOption_one,o=ProductOptionea_tow):(s+=ProductOption_one,_+=ProductOptionea_tow),w++)
if(w>0&&(t="묶음",p="&OptionCnt="+w+"&ProductOption="+s+"&ProductOptionea="+_),0==w)return void alert("구매하실 제품을 선택해주세요")}if("ProductList"==i){var C=v,k=!1,S=e,x=0
if(g=document.getElementById("AddGroupCount_"+u).value,g>1){for(var b=0;g>b;b++)1==document.getElementById("GroupNo_"+u+"_"+b).checked&&(0==x?(e=document.getElementById("GroupNo_"+u+"_"+b).value,o=document.getElementById("GroupProductea_"+u+"_"+b).value):(s+=document.getElementById("GroupNo_"+u+"_"+b).value+"|",_+=document.getElementById("GroupProductea_"+u+"_"+b).value+"|",C++,k=!0),x++)
if(1==k&&(p="&OptionCnt="+C+"&ProductOption="+s+"&ProductOptionea="+_+"&GroupState="+P,t="묶음",n="basket_insert_direct"==n||"option_insert_direct"==n?"option_insert_direct":"option_insert"),0==x)return void alert("구매 하실 품목을 선택 해주세요")}else o=document.getElementById("GroupProductea_"+u+"_0").value}if("p_new_list"==i&&void 0!=document.getElementById("GroupProductCnt_"+u)){var O=document.getElementById("GroupProductCnt_"+u).value,C=e=o=0
for(b=0;O>b;b++)void 0!=document.getElementById("SelGroupProductNo_"+u+"_"+b)&&document.getElementById("SelGroupProductNo_"+u+"_"+b).checked&&(e?(s+=document.getElementById("SelGroupProductNo_"+u+"_"+b).value+"|",_+=document.getElementById("SelGroupProductEa_"+u+"_"+b).value+"|"):(e=document.getElementById("SelGroupProductNo_"+u+"_"+b).value,o=document.getElementById("SelGroupProductEa_"+u+"_"+b).value),C++)
if(C||void 0!=document.getElementById("SelGroupProductNo_"+u)&&null!=document.querySelector("#SelGroupProductNo_"+u).getAttribute("ProductNo")&&(e=document.querySelector("#SelGroupProductNo_"+u).getAttribute("ProductNo"),o=1,C++),0==C)return void alert("구매하실 상품을 선택해 주세요.")
C--,C&&(p="&OptionCnt="+C+"&ProductOption="+s+"&ProductOptionea="+_+"&GroupState="+P,t="묶음",n="basket_insert_direct"==n||"option_insert_direct"==n?"option_insert_direct":"option_insert")}if(g=0,"ProductView"==i||"옵션"==t||"행사"==t||"일반"==t||"기획전"==t){var C=v,k=!1,S=e,x=0
if(null!=document.getElementById("AddPGNoCount")&&0<document.getElementById("AddPGNoCount").value){var g=document.getElementById("AddPGNoCount").value
if(void 0==document.global_form.add_PGNo_ProductNo){if("ProductView"==i)return void alert("구매하실 상품을 선택해주세요")}else{if(void 0==document.global_form.add_PGNo_ProductNo.length)var g="1"
else var g=document.global_form.add_PGNo_ProductNo.length
if(g>0){for(var b=0;g>b;b++){if(S=void 0==document.global_form.add_PGNo_ProductNo.length?document.global_form.add_PGNo_ProductNo.value:document.global_form.add_PGNo_ProductNo[b].value,0==x&&"ProductView"==i){if(e=S,o=document.getElementById("last_"+S).value,null!=document.getElementById("add_Color_"+S)){if(""==document.getElementById("add_Color_"+S).value)return alert("선택하신 제품코드 "+S+"번의 구매옵션을 선택해 주세요."),void(L="Y")
f=document.getElementById("add_Color_"+S).value}}else{if(s+=S+"|",_+=document.getElementById("last_"+S).value+"|",null!=document.getElementById("add_Color_"+S)){if(""==document.getElementById("add_Color_"+S).value)return alert("선택하신 제품코드 "+S+"번의 구매옵션을 선택해 주세요."),void(L="Y")
ProductOptionColor+=document.getElementById("add_Color_"+S).value+"|"}else ProductOptionColor+="|"
C++,k=!0}x++}if("Y"==L)return
if(1==k&&(p="&OptionCnt="+C+"&ProductOption="+s+"&ProductOptionea="+_+"&ProductOptionColor="+ProductOptionColor+"&GroupState="+P,t="묶음","basket_insert_direct"==n||"option_insert_direct"==n?n="option_insert_direct":"event_insert"==n||"event_call_insert"==n?t="행사":n="option_insert"),0==x)return void alert("구매 하실 품목을 선택 해주세요")}else o=document.getElementById("GroupProductea_"+e+"_0").value}}if("행사"==a&&(358973==e||359019==e||359011==e||359012==e||359013==e||359014==e||359015==e||359016==e||359017==e||359018==e))return void alert("해당 제품은 조립비 옵션을 필수로 선택하셔야 구매가 가능합니다.")
if(null!=document.getElementById("AddGroupCount")){var g=document.getElementById("AddGroupCount").value
if(void 0==document.global_form.add_ProductNo){if(358973==e||359019==e||359011==e||359012==e||359013==e||359014==e||359015==e||359016==e||359017==e||359018==e)return void alert("해당 제품은 조립비 옵션을 필수로 선택하셔야 구매가 가능합니다.")}else{if(void 0==document.global_form.add_ProductNo.length)var g="1"
else var g=document.global_form.add_ProductNo.length
var G="N",T=0,L=""
if(g>0){for(var b=0;g>b;b++){if(S=void 0==document.global_form.add_ProductNo.length?document.global_form.add_ProductNo.value:document.global_form.add_ProductNo[b].value,3877==S&&(G="Y",T=document.getElementById("last_"+S).value),0==x&&"ProductView"==i)e=S,o=document.getElementById("last_"+S).value
else{if(s+=S+"|",_+=document.getElementById("last_"+S).value+"|",null!=document.getElementById("add_Color_"+S)){if(""==document.getElementById("add_Color_"+S).value)return alert("추가상품으로 선택하신 제품코드 "+S+"번의 구매옵션을 선택해 주세요."),void(L="Y")
ProductOptionColor+=document.getElementById("add_Color_"+S).value+"|"}else ProductOptionColor+="|"
C++,k=!0}x++}if("Y"==L)return
if(358973==e||359019==e||359011==e||359012==e||359013==e||359014==e||359015==e||359016==e||359017==e||359018==e){if("N"==G)return void alert("해당 제품은 조립비 옵션을 필수로 선택하셔야 구매가 가능합니다.")
if("Y"==G&&document.getElementById("last_ea1").value!=T)return void alert("구매수량과 조립비의 수량이 동일해야 구매가 가능합니다")}if(1==k&&(p="&OptionCnt="+C+"&ProductOption="+s+"&ProductOptionea="+_+"&ProductOptionColor="+ProductOptionColor+"&GroupState="+P,t="묶음","basket_insert_direct"==n||"option_insert_direct"==n?n="option_insert_direct":"event_insert"==n||"event_call_insert"==n?t="행사":n="option_insert"),0==x)return void alert("구매 하실 품목을 선택 해주세요")}else o=document.getElementById("GroupProductea_"+e+"_0").value}}}if(null!=document.getElementById("AddInkTonerCount")&&document.getElementById("AddInkTonerCount").value>0){for(var Y=v,A=!1,j=0;j<document.getElementById("AddInkTonerCount").value;j++)1==document.getElementById("InkToner_"+j).checked&&(s+=document.getElementById("InkToner_"+j).value+"|",_+="1|",Y++,A=!0)
1==A&&(p="&OptionCnt="+Y+"&ProductOption="+s+"&ProductOptionea="+_+"&GroupState="+P,t="옵션",n="basket_insert_direct"==n||"option_insert_direct"==n?"option_insert_direct":"option_insert")}if(("basket_insert_direct"==n||"basket_insert_direct2"==n)&&"basket_insert_direct2"==n)if("prvcmp"==a){var D=document.getElementById("DeliveryTime_txt").value
alert("해당 제품은 공급업체 직발송 /별도배송 제품입니다.\n이 제품은 다른 제품과 별도 배송되며 배송기간이 "+D+"일 정도 소요됩니다."),n="basket_insert_direct"}else alert("해당 제품은 공급업체 직발송 /별도배송 제품입니다.\n이 제품은 다른 제품과 별도 배송되며 배송기간이 2~5일 소요됩니다."),n="basket_insert_direct"
if(("option_insert_direct"==n||"option_insert_direct2"==n)&&"option_insert_direct2"==n)if("prvcmp"==a){var D=document.getElementById("DeliveryTime_txt").value
alert("해당 제품은 공급업체 직발송 /별도배송 제품입니다.\n이 제품은 다른 제품과 별도 배송되며 배송기간이 "+D+"일 정도 소요됩니다."),n="option_insert_direct"}else alert("해당 제품은 공급업체 직발송 /별도배송 제품입니다.\n이 제품은 다른 제품과 별도 배송되며 배송기간이 2~5일 소요됩니다."),n="option_insert_direct"
if(window.sessionStorage&&window.history&&window.history.pushState){var z=document.location.href
if(-1!=z.indexOf("product_list.htm")||-1!=z.indexOf("search.htm")||-1!=z.indexOf("eventzone_view.htm")){-1!=z.indexOf("product_list.htm")?(window.sessionStorage.setItem("sessList",$(".product_list_wrap").html()),window.sessionStorage.setItem("sessStartNum",$("#StartNum").val()),window.sessionStorage.setItem("sessPageNum",$("#PageNum").val())):-1!=z.indexOf("eventzone_view.htm")?(window.sessionStorage.setItem("sessEvtList",$("#prd_list").html()),window.sessionStorage.setItem("sessPageIdx",$("#DefPageNo").val()),window.sessionStorage.setItem("EventNo",$("#EventNo").val())):(window.sessionStorage.setItem("sessSchDivSearch",$("#DivSearchOpt").html()),window.sessionStorage.setItem("sessSchDivOpt",$("#div_opt").html()),window.sessionStorage.setItem("sessSchCateList",$("#search_cateList").html()),window.sessionStorage.setItem("sessStartNum",$("#StartNum").val()),window.sessionStorage.setItem("sessPageNum",$("#PageNum").val()))
var V=Math.floor((new Date).getTime()/1e3)+600
z.indexOf("sessStrgExp")<=0&&(-1!=z.indexOf("#")?z=z.replace(/#/gi,"&sessStrgExp="+V+"#"):z+=(z.split("?")[1]?"&":"?")+"sessStrgExp="+V,window.history.pushState(null,null,z))}}if(!f)if("1"==r){if(null!=document.getElementById("Color"))if(""!=document.getElementById("Color").value)f=document.getElementById("Color").value
else{if("search"!=a)return alert("지금 선택하신 제품은 색상 선택 제품입니다.\n\n 색상을 선택해주세요!"),void("prlist"==a&&(location.href="../product/product_detail.htm?ProductNo="+e))
alert("기본 색상으로 선택됩니다.\n\n 장바구니에서 변경해주세요!")}else if(!g||0==g){if("search"!=a)return alert("지금 선택하신 제품은 색상 선택 제품입니다.\n\n 색상을 선택해주세요!"),void("prlist"==a&&(location.href="../product/product_detail.htm?ProductNo="+e))
alert("기본 색상으로 선택됩니다.\n\n 장바구니에서 변경해주세요!")}}else if("2"==r){if(null!=document.getElementById("Color")){if(""==document.getElementById("Color").value)return alert("지금 선택하신 제품은 사은품이 있습니다.\n\n 사은품을 선택해주세요!"),void("prlist"==a&&(location.href="../product/product_detail.htm?ProductNo="+e))
f=document.getElementById("Color").value}else if(!g||0==g)return alert("지금 선택하신 제품은 사은품이 있습니다.\n\n 사은품을 선택해주세요!"),void("prlist"==a&&(location.href="../product/product_detail.htm?ProductNo="+e))}else if("3"==r)if(null!=document.getElementById("Color")){if(""==document.getElementById("Color").value)return alert("지금 선택하신 제품은 옵션이 있습니다.\n\n 옵션을 선택해주세요!"),void("prlist"==a&&(location.href="../product/product_detail.htm?ProductNo="+e))
f=document.getElementById("Color").value}else if(!g||0==g)return alert("지금 선택하신 제품은 옵션이 있습니다.\n\n 옵션을 선택해주세요!"),void("prlist"==a&&(location.href="../product/product_detail.htm?ProductNo="+e))
if(null!=document.getElementById("use_coupon"))var X=document.getElementById("use_coupon").value
else var X=""
var F=""
null!=document.getElementById("DeliveryPriceType")&&(F=document.getElementById("DeliveryPriceType").value)
var q="../order/order_function.php?actype="+n+"&from_where="+t+"&cProductNo="+e+"&cProductEa="+o+"&cColor="+f+"&cUseCoupon="+X+p+"&InputPage="+a+"&DeliveryPriceType="+F
if(y&&(q+="&tenThousandEvtCnt="+y),"일반"==t||"기획전"==t)if("basket_insert_detail"==n)window.open(q,"","width=1,height=1")
else if("option_insert_direct"==n)window.open(q,"","width=1200,height=1000,scrollbars=yes")
else if(null!=document.getElementById("common_iframe"))if("basket_insert_detail2"==n)if("partsView_Box"==i)document.getElementById("common_iframe").src=q+"&isPage="+document.getElementById("isPagePartSpec").value+"&orderlayer_parts_x="+document.getElementById("orderlayer_parts_x").value+"&orderlayer_parts_y="+document.getElementById("orderlayer_parts_y").value
else if("iwView_Box"==i)document.getElementById("common_iframe").src=q+"&isPage="+document.getElementById("isPageIwSpec").value+"&orderlayer_iworks_x="+document.getElementById("orderlayer_iworks_x").value+"&orderlayer_iworks_y="+document.getElementById("orderlayer_iworks_y").value
else{var W=150,H=W/2,M=document.documentElement.scrollTop,R=document.documentElement.scrollLeft
0==M&&(M=document.body.scrollTop),0==R&&(R=document.body.scrollLeft),document.global_form.orderlayery.value=d.clientY+M-H-90+"px",document.global_form.orderlayerx.value=d.clientX+R-270+"px",document.getElementById("common_iframe").src=q}else if("basket_insert_detail3"==n){var W=150,H=W/2,M=document.documentElement.scrollTop,R=document.documentElement.scrollLeft
0==M&&(M=document.body.scrollTop),0==R&&(R=document.body.scrollLeft),document.global_form.orderlayery.value=d.clientY+M-H-90+"px",document.global_form.orderlayerx.value=d.clientX+R-270+"px",document.getElementById("common_iframe").src=q}else document.location.href=q
else document.location.href=q
else if("행사"==t){if("event_insert"!=n){var q="../order/order_function.php?actype=event_call_insert&event_sale_no="+e+p+"&cColor="+f+"&InputPage="+a
return void(document.location.href=q)}var W=150,H=W/2,M=document.documentElement.scrollTop,R=document.documentElement.scrollLeft
0==M&&(M=document.body.scrollTop),0==R&&(R=document.body.scrollLeft),document.global_form.orderlayerx.value=d.clientY+M-H-90+"px",document.global_form.orderlayery.value=d.clientX+R-270+"px"
var U="&cColor="+f+"&EventSaleReturnBack="
document.getElementById("common_iframe").src=q+"&event_sale_no="+e+U}else if("팝업"==t)document.location.href=q+"&after=opener"
else if("옵션"==t||"묶음"==t)if("option_insert_direct"==n)document.location.href=q
else if(null!=document.getElementById("common_iframe")){var W=150,H=W/2,M=document.documentElement.scrollTop,R=document.documentElement.scrollLeft
0==M&&(M=document.body.scrollTop),0==R&&(R=document.body.scrollLeft),document.global_form.orderlayerx.value=d.clientY+M-H-90+"px",document.global_form.orderlayery.value=d.clientX+R-170+"px",document.getElementById("common_iframe").src=q}else document.location.href=q}function detail_show(e){var t=parseInt(e)
t>0?(where_go="../product/product_detail.htm?ProductNo="+e+"&opt_chk=Y",window_open(where_go,1200,700,"scrollbars=yes,resizable=yes","")):alert("제품번호가 정확하지 않습니다!")}function detail_show_iworks(e){var t=parseInt(e)
t>0?(where_go="http://www.compuzone.co.kr/product/iworks_detail.htm?ProductNo="+e,window_open(where_go,1200,700,"scrollbars=yes,resizable=yes","")):alert("제품번호가 정확하지 않습니다!")}function detail_show_group(e){var t=parseInt(e)
t>0?(where_go="http://www.compuzone.co.kr/pop_page/product_simple_detail.htm?ProductNo="+e,window_open(where_go,780,500,"scrollbars=yes","")):alert("제품번호가 정확하지 않습니다!")}function detail_show_loop(form_name,num,ele_name){var pre_product_no=eval("document."+form_name+'.elements["'+ele_name+'"]['+num+"].value"),split_value=pre_product_no.split("|"),product_no=split_value[0]
detail_show(product_no)}function check_all(obj,ele_name){if(void 0!=eval('obj.elements["'+ele_name+'"]')){var len=eval('obj.elements["'+ele_name+'"].length')
if(void 0==len)eval('obj.elements["'+ele_name+'"].checked = !obj.elements["'+ele_name+'"].checked')
else for(var i=0;len>i;i++)eval('obj.elements["'+ele_name+'"]['+i+'].checked = !obj.elements["'+ele_name+'"]['+i+"].checked")}}function now_allow_adult_layer(){var e='<div id="error_layer" style="z-index:9999;width:778px; padding:20px; height:200px; background-color:#f9f9f9; border:1px solid #e6e6e6; margin:0 auto; border-top:none; display:none;">'
e+=' <div class="Wbox" style="width:778px; height:auto; border:1px solid #e6e6e6; float:left; background-color:#FFF; padding:10px 0 30px 0;">',e+=' 	<div class="tit" style="width:486px; height:100px; float:left; margin:5px 146px;">',e+=" 		<div class='mbr3' style='width:486px; height:100px; background:url(\"https://www.compuzone.co.kr/login_main/img/2013_login.jpg\") no-repeat -477px -1029px; display:block; text-indent:-10000px; margin:15px 0;'>죄송합니다</div>",e+=" 	</div>",e+=' 	<div class="okbtn" style="width:778px; height:26px; float:left; margin-top:20px;">',e+=" 		<a href='javascript:void(0);' onclick='mov_link(\"../main/main.htm\");'>",e+=" 			<div class='btn' style='display:block; width:58px; height:26px; background:url(\"../login_main/img/2013_login.jpg\") no-repeat -259px 0px; margin:0 auto; float:left; margin:0 360px; text-indent:-10000px;'>확인</div>",e+=" 		</a>",e+=" 	</div>",e+=" </div>",e+="</div>"
var t=$(e)
$("body").prepend(t)
var o=document.documentElement&&document.documentElement.scrollTop||document.body.scrollTop,r=document.documentElement&&document.documentElement.scrollLeft||document.body.scrollLeft,n=document.body.clientHeight/2-$("#error_layer").height()/2+o,l=document.body.clientWidth/2-$("#error_layer").width()/2+r
$("#error_layer").css({position:"absolute",top:n,left:l}).show()}function mov_link(e){document.location.href=e}